# Generated by Django 5.1.1 on 2024-10-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_movies_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='image',
            field=models.ImageField(default='media/missing_movie_image.jpg', upload_to='movies/'),
        ),
    ]
