# Generated by Django 5.1.2 on 2024-10-13 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_seats_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='seat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cinema_app.seats'),
        ),
    ]
