# Generated by Django 5.1.2 on 2024-10-13 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0003_alter_tickets_seat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seats',
            name='is_available',
        ),
    ]
