# Generated by Django 5.1.2 on 2024-10-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_remove_seats_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='quantity',
        ),
    ]
